export const watchesData = [
  {
    category: "Man",
    collection: "Classic Men's",
    trending: [
      "Allied GMT",
      "Easy Reader",
      "Waterbury World Time",
      "Expedition",
      "City Collection",
    ],
    watchType: [
      "Chronograph",
      "Leather",
      "Dive",
      "Automatic",
      "Digital",
      "Smart",
      "Pilot",
    ],
    byCollection: [
      "Fairfield",
      "Easy Reader",
      "Expedition",
      "Waterbury",
      "City Collection",
      "Ironman",
      "Weekender",
    ],
  },
  {
    category: "Women",
    collection: "Elegant Women's",
    trending: ["Scarlette", "Bella", "Riley", "Gigi", "Georgia"],
    watchType: [
      "Analog",
      "Digital",
      "Fashion",
      "Fitness",
      "Dress",
      "Smart",
      "Casual",
    ],
    byCollection: [
      "Scarlette",
      "Bella",
      "Riley",
      "Gigi",
      "Georgia",
      "Charlotte",
      "Sofie",
    ],
  },
  {
    category: "Kids",
    collection: "Fun Kids'",
    trending: [
      "Time Teacher",
      "Kid's Sports",
      "Character Watches",
      "Colorful Straps",
      "Adventure Series",
    ],
    watchType: [
      "Analog",
      "Digital",
      "Sports",
      "Cartoon",
      "Water-resistant",
      "Educational",
      "Fun",
    ],
    byCollection: [
      "Time Teacher",
      "Kid's Sports",
      "Character Watches",
      "Colorful Straps",
      "Adventure Series",
      "Animals",
      "Learning",
    ],
  },
  {
    category: "Sale Straps",
    collection: "Strap Sale",
    trending: [
      "Nylon Straps",
      "Silicone Bands",
      "Leather Bands",
      "Metal Bracelets",
      "Rubber Straps",
    ],
    watchType: [
      "Replacement Straps",
      "Accessories",
      "Buckles",
      "Deployment Clasps",
      "Quick Release",
      "Interchangeable",
      "Fashion Straps",
    ],
    byCollection: [
      "Nylon Straps",
      "Silicone Bands",
      "Leather Bands",
      "Metal Bracelets",
      "Rubber Straps",
      "Mesh Bands",
      "Vintage Straps",
    ],
  },
];
